################################################
# Other Files
################################################

[[plugins]] # markdownのシンタックス
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']

[[plugins]] # markdownのtableの整形
repo = 'godlygeek/tabular'
on_ft = ['markdown', 'mkd']

[[plugins]] # markdownのクゥオート内シンタックス
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown', 'mkd']

[[plugins]] # markdownのPreview
repo = 'kannokanno/previm'
on_ft = ['markdown', 'mkd']

[[plugins]] # ブラウザ起動
repo = 'tyru/open-browser.vim'
on_ft = ['markdown', 'mkd']

[[plugins]] # tomlのシンタックス
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # jsonのシンタックス
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]] # 直接DB触ったりSQL補完したり
repo = 'vim-scripts/dbext.vim'
on_ft = 'sql'
