################################################
# Ruby
################################################

[[plugins]] # def end の自動入力
repo = 'tpope/vim-endwise.git'
on_ft = ['ruby', 'eruby']

[[plugins]] # 
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby', 'eruby']

[[plugins]] # Railsプロジェクト用プラグイン
repo = 'taichouchou2/vim-rails'
hook_post_source = '''
  let g:rails_no_abbreviations = 1
'''
on_ft = ['ruby', 'eruby']

[[plugins]] # Railsプロジェクト用プラグイン
repo = 'romanvbabenko/rails.vim'
on_ft = ['ruby', 'eruby']

[[plugins]] # RSpecをvimから実行
repo = 'thoughtbot/vim-rspec'
on_ft = ['ruby', 'eruby']
